name: 'Lighthouse Check Status'
description: 'A GitHub Action used to handle output from "foo-software/lighthouse-check-action" and determine workflow status.'
branding:
  icon: 'zap'  
  color: 'green'
inputs:
  lighthouseCheckResults:
    description: 'A results object representing results of Lighthouse audits.'
    required: true
  minAccessibilityScore:
    description: 'The minimum accessibility Lighthouse score required.'
  minBestPracticesScore:
    description: 'The minimum best practices Lighthouse score required.'
  minPerformanceScore:
    description: 'The minimum performance Lighthouse score required.'
  minProgressiveWebAppScore:
    description: 'The minimum progressive web app Lighthouse score required.'
  minSeoScore:
    description: 'The minimum SEO Lighthouse score required.'
runs:
  using: 'node12'
  main: 'index.js'
