name: 'Lighthouse Check Status'
description: 'A GitHub Action used to handle output from "foo-software/lighthouse-check-action" and determine workflow status.'
branding:
  icon: 'zap'  
  color: 'green'
inputs:
  lighthouseCheckResults:
    description: 'A results object representing results of Lighthouse audits.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
