name: Test Lighthouse Check Status
on: [push]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/bin/debug@master
    - run: npm install
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        urls: 'https://www.foo.software,https://www.foo.software/contact'
    - name: Handle Lighthouse Check results
      uses: ./
      with:
        lighthouseCheckResults: ${{ toJson(steps.lighthouseCheck.outputs.lighthouseCheckResults) }}
        minAccessibilityScore: 90
        minBestPracticesScore: 50
        minPerformanceScore: 50
        minProgressiveWebAppScore: 50
        minSeoScore: 50
